export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATION = 'DELETE_ALL_NOTIFICATION';

export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';

export const NOTIFICATION_CREATE_REQUEST = 'NOTIFICATION_CREATE_REQUEST';
export const NOTIFICATION_CREATE_SUCCESS = 'NOTIFICATION_CREATE_SUCCESS';
export const NOTIFICATION_CREATE_FAIL = 'NOTIFICATION_CREATE_FAIL';
export const NOTIFICATION_CREATE_RESET = 'NOTIFICATION_CREATE_RESET';

export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_FAIL = 'NOTIFICATION_DELETE_FAIL';
export const NOTIFICATION_DELETE_RESET = 'NOTIFICATION_DELETE_RESET';

export const NOTIFICATION_DELETE_ALL_REQUEST = 'NOTIFICATION_DELETE_ALL_REQUEST';
export const NOTIFICATION_DELETE_ALL_SUCCESS = 'NOTIFICATION_DELETE_ALL_SUCCESS';
export const NOTIFICATION_DELETE_ALL_FAIL = 'NOTIFICATION_DELETE_ALL_FAIL';
export const NOTIFICATION_DELETE_ALL_RESET = 'NOTIFICATION_DELETE_ALL_RESET';
